### ISSUE TITLE
Advanced page for remote domain

### ISSUE THREAD

**Issue by AlexanderSamokhin** [Tulpep/Active-Directory-Object-Picker#15] opened 2016-06-24 16:16 UTC
Is it possible to open Advanced Page for remote domain?

![err](https://cloud.githubusercontent.com/assets/20129703/16343490/16414e0c-3a40-11e6-8849-5261bc3ca624.png)

**Comment by ricardopolo** [comment] 2017-08-24 02:58
If someone help us duing this, we well happy approve the PR 😄

**Comment by MarcelGosselin** [comment] 2017-08-26 14:20
The error message says:

> The server is not operational.

so I wonder whether it is:

1. a problem in this library
1. a problem with your current setup
1. simply impossible to display this dialog for remote domains

To narrow it down, could you try changing the security on a folder and in the _Select User..._ dialog that opens, try to open the _Advanced_ dialog for the same remote domain. If it opens, the problem is the first option and if you receive the same error message, the problem is either option 2 or 3.

**Comment by ricardopolo** [comment] 2020-01-27 04:18
Closing due not activity. Fell free to reopen if necessary.

**Closed by ricardopolo** 2020-01-27 04:18 UTC
