### ISSUE TITLE
Allow user to pass in initial selection

### ISSUE THREAD

**Issue by MCFHTAGENTS** [Tulpep/Active-Directory-Object-Picker#27] opened 2018-06-30 07:29 UTC
Looking at this API please can it be enhanced such that you can pass in a AD Object and this becomes the initial selection.
Thanks
Mark

**Comment by ricardopolo** [comment] 2018-06-30 15:11
I don’t have to implement this feature now. However, if you can make a Pr that makes that I will be happy to approve it and release a new nugget version. 

Thanks

**Comment by dahall** [comment] 2018-07-03 22:44
Duplicate of #16

**Comment by ricardopolo** [comment] 2018-07-04 02:10
Closing this. Lets talk in #16

**Closed by ricardopolo** 2018-07-04 02:10 UTC
